"""
Comprehensive fix for resistance_genes.db:
- Sequences verified from CARD (McMaster) and NCBI RefSeq
- Browser-collected sequences hardcoded directly
- blashv-1 fetched fresh from NCBI via Biopython
- blaCTX-M-8 extracted from AF189721
- blaTEM-1_variant: remove corrupt '.' character
- 3 SNP markers left empty (require manual literature sequences)
"""
import sqlite3
import re
from Bio import Entrez, SeqIO

Entrez.email = "repair@aris.tool"

# ================================================================
# SEQUENCES VERIFIED FROM CARD / NCBI (via browser collection)
# ================================================================
SEQUENCES = {
    # --- CARD-verified sequences ---
    "sul2": (
        "ATGAATAAATCGCTCATCATTTTCGGCATCGTCAACATAACCTCGGACAGTTTCTCCGATGGAGGCCGGTATCTGGCGCC"
        "AGACGCAGCCATTGCGCAGGCGCGTAAGCTGATGGCCGAGGGGGCAGATGTGATCGACCTCGGTCCGGCATCCAGCAATC"
        "CCGACGCCGCGCCTGTTTCGTCCGACACAGAAATCGCGCGTATCGCGCCGGTGCTGGACGCGCTCAAGGCAGATGGCATT"
        "CCCGTCTCGCTCGACAGTTATCAACCCGCGACGCAAGCCTATGCCTTGTCGCGTGGTGTGGCCTATCTCAATGATATTCG"
        "CGGTTTTCCAGACGCTGCGTTCTATCCGCAATTGGCGAAATCATCTGCCAAACTCGTCGTTATGCATTCGGTGCAAGACG"
        "GGCAGGCAGATCGGCGCGAGGCACCCGCTGGCGACATCATGGATCACATTGCGGCGTTCTTTGACGCGCGCATCGCGGCG"
        "CTGACGGGTGCCGGTATCAAACGCAACCGCCTTGTCCTTGATCCCGGCATGGGGTTTTTTCTGGGGGCTGCTCCCGAAACC"
        "TCGCTCTCGGTGCTGGCGCGGTTCGATGAATTGCGGCTGCGCTTCGATTTGCCGGTGCTTCTGTCTGTTTCGCGCAAATC"
        "CTTTCTGCGCGCGCTCACAGGCCGTGGTCCGGGGGATGTCGGGGCCGCGACACTCGCTGCAGAGCTTGCCGCCGCCGCAGG"
        "TGGAGCTGACTTCATCCGCACACACGAGCCGCGCCCCTTGCGCGACGGGCTGGCGGTATTGGCGGCGCTGAAAGAAACCGC"
        "AAGAATTCGTTAA"
    ),

    "tet(m)": (
        "ATGAAAATTATTAATATTGGAGTTTTAGCTCATGTTGATGCGGGAAAAACTACCTTAACAGAAAGCTTATTATATAACAGTG"
        "GAGCGATTACAGAATTAGGAAGCGTGGACAAAGGTACAACGAGGACGGATAATACGCTTTTAGAACGTCAGAGAGGAATTAC"
        "AATTCAGACAGGAATAACCTCTTTTCAGTGGGAAAATACGAAGGTGAACATCATAGACACGCCAGGACATATGGATTTCTTA"
        "GCAGAAGTATATCGTTCATTATCAGTTTTAGATGGGGCAATTCTACTGATTTCTGCAAAAGATGGCGTACAAGCACAAACTC"
        "GTATATTATTTCATGCACTTAGGAAAATGGGGATTCCCACAATCTTTTTTATCAATAAGATTGACCAAAATGGAATTGATTT"
        "ATCAACGGTTTATCAGGATATTAAAGAGAAACTTTCTGCCGAAATTGTAATCAAACAGAAGGTAGAACTGTATCCTAATATG"
        "TGTGTGACGAACTTTACCGAATCTGAACAATGGGATACGGTAATAGAGGGAAACGATGACCTTTTAGAGAAATATACGTCTG"
        "GGAAATTATTGGAAGCATTAGAACTCGAACAAGAGGAAAGCATAAGATTTCATAATTGTTCCCTGTTCCCTGTTTATCACGG"
        "AAGTGCAAAAAACAATATAGGGATTGATAACCTTATAGAAGTGATTACGAATAAATTTTATTCATCAACACATCGAGGTCAG"
        "TCTGAACTTTGCGGAAAAGTTTTCAAAATTGAATATACAAAAAAAAGACAACGTCTTGCATATATACGCCTTTATAGTGGAG"
        "TACTACATTTACGAGATTCGGTTAGAGTATCAGAAAAAGAAAAAATAAAAGTTACAGAAATGTATACTTCAATAAATGGTGA"
        "ATTATGTAAGATTGATAGAGCTTATTCTGGAGAAATTGTTATTTTGCAAAATGAGTTTTTGAAGTTAAATAGTGTTCTTGGA"
        "GATACAAAACTATTGCCACAGAGAAAAAAGATTGAAAATCCGCACCCTCTACTACAAACAACTGTTGAACCGAGTAAACCTG"
        "AACAGAGAGAAATGTTGCTTGATGCCCTTTTGGAAATCTCAGATAGTGATCCGCTTCTACGATATTACGTGGATTCTACGAC"
        "ACATGAAATTATACTTTCTTTCTTAGGGAAAGTACAAATGGAAGTGATTAGTGCACTGTTGCAAGAAAAGTATCATGTGGAG"
        "ATAGAACTAAAAGAGCCTACAGTCATTTATATGGAGAGACCGTTAAAAAATGCAGAATATACCATTCACATCGAAGTGCCGCC"
        "AAATCCTTTCTGGGCTTCCATTGGTTTATCTGTATCACCGCTTCCGTTGGGAAGTGGAATGCAGTATGAGAGCTCGGTTTCT"
        "CTTGGATACTTAAATCAATCATTTCAAAATGCAGTTATGGAGGGGATACGCTATGGCTGTGAACAAGGATTGTATGGTTGGA"
        "ATGTGACGGACTGTAAAATCTGTTTTAAGTATGGCTTATACTATAGCCCTGTTAGTACCCCAGCAGATTTTCGGATGCTTGC"
        "TCCTATTGTATTGGAACAAGTCTTAAAAAAAGCTGGAACAGAATTGTTAGAGCCATATCTTAGTTTTAAAATTTATGCGCCAC"
        "AGGAATATCTTTCACGAGCATACAACGATGCTCCTAAATATTGTGCGAACATCGTAGACACTCAATTGAAAAATAATGAGGT"
        "CATTCTTAGTGGAGAAATCCCTGCTCGGTGTATTCAAGAATATCGTAGTGATTTAACTTTCTTTACAAATGGACGTAGTGTTT"
        "GTTTAACAGAGTTAAAAGGGTACCATGTTACTACCGGTGAACCTGTTTGCCAGCCCCGTCGTCCAAATAGTCGGATAGATAA"
        "AGTACGATATATGTTCAATAAAATAACTTAG"
    ),

    "blacmy-2": (
        "ATGATGAAAAAATCGTTATGCTGCGCGTCTGCTGCTGACAGCCTCTTTCTCCACATTTGCTGCCGCAAAAACAGAACAACAG"
        "ATTGCCGATATCGTTAATCGCACCATCACCCCGTTGATGCAGGAGCAGGCTATTCCGGGTATGGCCGTTGCCGTTATCTACC"
        "AGGGAAAACCCTATTATTTCACCTGGGGTAAAGCCGATATCGCCAATAACCACCCAGTCACGCAGCAAACGCTGTTTGAGCTA"
        "GGATCGGTTAGTAAGACGTTTAACGGCGTGTTGGGCGGCGATGCTATCGCCCGCGGCGAAATTAAGCTCAGCGATCCGGTCA"
        "CGAAATACTGGCCAGAACTGACAGGCAAACAGTGGCAGGGTATCCGCCTGCTGCACTTAGCCACCTATACGGCAGGCGGCCTA"
        "CCGCTGCAGATCCCCGATGACGTTAGGGATAAAGCCGCATTACTGCATTTTTATCAAAACTGGCAGCCGCAATGGACTCCGGG"
        "CGCTAAGCGACTTTACGCTAACTCCAGCATTGGTCTGTTTGGCGCGCTGGCCGTGAAACCCTCAGGAATGAGTTACGAAGAGG"
        "CAATGACCAGACGCGTCCTGCAACCATTAAAACTGGCGCATACCTGGATTACGGTTCCGCAGAACGAACAAAAAGATTATGCT"
        "GGGGCTATGCGCGAAGGAAGCCCGTACACGTTTCTCCGGGAGCAACTTGACGCCGAAGCCTATGGCGTGAAATCCAGCGTTAT"
        "TGATATGGCCCGCTGGGTTCAGGCCAACATGGATGCCAGCCACGTTCAGGAGAAAACGCTCCAGCAGGGGATTGCGCTTGCGC"
        "AGTCTCGCTACTGGCGTATTGGCGATATGTACCAGGGATTAGGCTGGGAGATGCTGAACTGGCCGCTGAAAGCTGATTCGATC"
        "ATCAACGGCAGCGACAGCAAAGTGGCATTGGCAGCGCTTCCCGCTTGGAGGTAAACCCGCCCGCCCCGCAGTGAAAGCCTCAT"
        "GGGTGCATAAAACGGGCTCCACTGGTGGATTTGGCAGCTACGTAGCCTTCGTTCCAGAAAAAAACCTTGGCATCGTGGTGGCA"
        "AACAAAAGCTATGCTAACCCTGTCCGTGTCGAGGCGGCCTGGCGCATTCTTGAAAAGCTGCAATAA"
    ),

    # blaCMY (generic/parent) — use CMY-2 as the reference representative
    "blacmy": (
        "ATGATGAAAAAATCGTTATGCTGCGCGTCTGCTGCTGACAGCCTCTTTCTCCACATTTGCTGCCGCAAAAACAGAACAACAG"
        "ATTGCCGATATCGTTAATCGCACCATCACCCCGTTGATGCAGGAGCAGGCTATTCCGGGTATGGCCGTTGCCGTTATCTACC"
        "AGGGAAAACCCTATTATTTCACCTGGGGTAAAGCCGATATCGCCAATAACCACCCAGTCACGCAGCAAACGCTGTTTGAGCTA"
        "GGATCGGTTAGTAAGACGTTTAACGGCGTGTTGGGCGGCGATGCTATCGCCCGCGGCGAAATTAAGCTCAGCGATCCGGTCA"
        "CGAAATACTGGCCAGAACTGACAGGCAAACAGTGGCAGGGTATCCGCCTGCTGCACTTAGCCACCTATACGGCAGGCGGCCTA"
        "CCGCTGCAGATCCCCGATGACGTTAGGGATAAAGCCGCATTACTGCATTTTTATCAAAACTGGCAGCCGCAATGGACTCCGGG"
        "CGCTAAGCGACTTTACGCTAACTCCAGCATTGGTCTGTTTGGCGCGCTGGCCGTGAAACCCTCAGGAATGAGTTACGAAGAGG"
        "CAATGACCAGACGCGTCCTGCAACCATTAAAACTGGCGCATACCTGGATTACGGTTCCGCAGAACGAACAAAAAGATTATGCT"
        "GGGGCTATGCGCGAAGGAAGCCCGTACACGTTTCTCCGGGAGCAACTTGACGCCGAAGCCTATGGCGTGAAATCCAGCGTTAT"
        "TGATATGGCCCGCTGGGTTCAGGCCAACATGGATGCCAGCCACGTTCAGGAGAAAACGCTCCAGCAGGGGATTGCGCTTGCGC"
        "AGTCTCGCTACTGGCGTATTGGCGATATGTACCAGGGATTAGGCTGGGAGATGCTGAACTGGCCGCTGAAAGCTGATTCGATC"
        "ATCAACGGCAGCGACAGCAAAGTGGCATTGGCAGCGCTTCCCGCTTGGAGGTAAACCCGCCCGCCCCGCAGTGAAAGCCTCAT"
        "GGGTGCATAAAACGGGCTCCACTGGTGGATTTGGCAGCTACGTAGCCTTCGTTCCAGAAAAAAACCTTGGCATCGTGGTGGCA"
        "AACAAAAGCTATGCTAACCCTGTCCGTGTCGAGGCGGCCTGGCGCATTCTTGAAAAGCTGCAATAA"
    ),

    "blactx-m-1": (
        "ATGGTTAAAAAATCACTGCGTCAGTTCACGCTGATGGCGACGGCAACCGTCACGCTGTTGTTAGGAAGTGTGCCGCTGTATG"
        "CGCAAACGGCGGACGTACAGCAAAAACTTGCCGAATTAGAGCGGCAGTCGGGAGGAAGACTGGGTGTGGCATTGATTAACAC"
        "AGCAGATAATTCGCAAATACTTTATCGTGCTGATGAGCGCTTTGCGATGTGCAGCACCAGTAAAGTGATGGCCGTGGCCGCG"
        "GTGCTGAAGAAAAGTGAAAGCGAACCGAATCTGTTAAATCAGCGAGTTGAGATCAAAAAATCTGACTTGGTTAACTATAATC"
        "CGATTGCGGAAAAGCACGTCGATGGGACGATGTCACTGGCTGAGCTTAGCGCGGCCGCGCTACAGTACAGCGATAACGTGGC"
        "GATGAATAAGCTGATTTCTCACGTTGGCGGCCCGGCTAGCGTCACCGCGTTCGCCCGACAGCTGGGAGACGAAACGTTCCGT"
        "CTCGACCGTACCGAGCCGACGTTAAACACCGCCATTCCGGGCGATCCGCGTGATACCACTTCACCTCGGGCAATGGCGCAAA"
        "CTCTGCGTAATCTGACGCTGGGTAAAGCATTGGGTGACAGCCAACGGGCGCAGCTGGTGACATGGATGAAAGGCAATACCAC"
        "CGGTGCAGCGAGCATTCAGGCTGGACTGCCTGCTTCCTGGGTTGTGGGGGATAAAACCGGCAGCGGTGACTATGGCACCACC"
        "AACGATATCGCGGTGATCTGGCCAAAAGATCGTGCGCCGCTGATTCTGGTCACTTACTTCACCCAGCCTCAACCTAAGGCAG"
        "AAAGCCGTCGCGATGTATTAGCGTCGGCGGCTAAAATCGTCACCAACGGTTTGTAA"
    ),

    # CTX-M-8 CDS extracted from AF189721 (start: ATGATGAGACATCGCG)
    "blactx-m-8": (
        "ATGATGAGACATCGCGTTAAGCGGATGATGCTAATGACAACGGCCTGTATTTCGCTGTTGCTGGGGAGTGCGCCGCTGTATG"
        "CGCAGGCGAACGACGTTCAGCAAAAGCTGGCGGCGCTGGAGAAAAGCAGCGGGGGGCGGTTGGGAGTGGCGCTGATTGACACC"
        "GCCGATAACGCACAGACGCTCTACCGCGCCGATGAGCGCTTTGCCATGTGCAGCACCAGTAAGGTGATGGCGGCAGCGGCTGT"
        "GCTCAAGCAAAGTGAAACGCAAAAGAAGGTGTTGAGTCAGAAGGTTGAGATTAAATCTTCAGACCTGATTAACTACAATCCCATT"
        "ACTGAAAAACACGTCAACGGCACGATGACGCTGGCGGAATTGAGCGCCGCGGCGTTGCAGTACAGCGACAATACGGCCATGAAC"
        "AAGCTGATTGCCCATCTTGGGGGGCCGGATAAGGTGACGGCGTTTGCCCGTGCGATTGGGGATAACACCTTCCGGCTCGATCGT"
        "ACTGAGCCGACGCTCAACACCGCGATCCCCGGCGACCCGCGCGATACCACCACGCCATTAGCGATGGCGCAGACGCTTCGCAAT"
        "CTGACGTTGGGCAGTGCCTTAGGTGAAACTCAGCGTGCGCAACTGGTAACGTGGCTGAAAGGCAATACCACCGGCGCTGCCAGC"
        "ATTCAGGCTGGGCTACCCACATCGTGGGTTGTCGGGATAAAACCGGCAGCGGTGATTATGGTACGACGAATGACATCGCCGTTA"
        "TCTGGCCGGAAGGGCGTGCGCCGCTTATTCTGGTCACTTACTTCACCCAGCCAGAGCAGAAGGCAGAAAGTCGTCGTGACGTAC"
        "TCGCGGCTGCCGCGAAAATCGTCACCGACGGTTATTAA"
    ),

    "aada5": (
        "ATGGGTGAATTTTTCCCTGCACAAGTTTTCAAGCAGCTGTCCCACGCTCGCGCGGTGATCGAGCGCCATCTGGCTGCGACACT"
        "GGACACAATCCACCTGTTCGGATCTGCGATCGATGGAGGGCTGAAGCCGGACAGCGACATAGACTTGCTCGTGACCGTCAGCG"
        "CCGCACCTAACGATTCGCTCCGGCAGGCGCTAATGCTCGATTTGCTGAAAGTCTCATCACCGCCAGGCGATGGCGGAACATGG"
        "CGACCGCTGGAGCTAACTGTTGTCGCTCGAAGCGAAGTAGTGCCTTGGCGCTATCCGGCGCGGCGTGAGCTTCAGTTCGGTGA"
        "GTGGCTCCGCCACGACATCCTTTCCGGAACGTTCGAGCCTGCCGTTCTGGATCACGATCTTGCGATTTTGCTGACCAAGGCGA"
        "GGCAACACAGCCTTGCGCTTCTAGGCCCATCCGCAGCCACGTTTTTCGAGCCGGTGCCGAAGGAGCATTTCTCCAAGGCGCTT"
        "TTCGACACTATTGCCCAGTGGAATGCAGAGTCGGATTGGAAGGGTGACGAGCGGAACGTCGTTCTTGCTCTTGCTCGCATTTG"
        "GTACAGCGCTTCAACTGGTCTCATTGCTCCTAAGGACGTTGCTGCCGCATGGGTATCGGAGCGTTTGCCTGCCGAGCATCGGC"
        "CCCTCATCTGCAAGGCACGCGCGGCGTACCTGGGTAGCGAGGACGACGACCTAGCAATGCGCGTCGAAGAGACGGCCGCGTTC"
        "GTTCGATATGCCAAAGCAACGATTGAGAGAATCTTGCGTTGA"
    ),

    "dfra7": (
        "TTGAAAATTTCATTGATTTCTGCAACGTCAGAAAATGGCGTAATCGGTAATGGCCCTGATATCCCATGGTCAGCAAAAGGTGA"
        "GCAGTTACTCTTTAAAGCGCTCACATATAATCAGTGGCTCCTTGTTGGAAGGAAAACATTTGACTCTATGGGTGTTCTTCCAA"
        "ATCGAAAATATGCAGTAGTGTCGAGGAAAGGAATTTCAAGCTCAAATGAAAATGTATTAGTCTTTCCTTCAATAGAAATCGCT"
        "TTGCAAGAACTATCGAAAATTACAGATCATTTATATGTCTCTGGTGGCGGTCAAATCTACAATAGTCTTATTGAAAAAGCAGAT"
        "ATAATTCATTTGTCTACTGTTCACGTTGAGGTTGAAGGTGATATCAATTTTCCTAAAATTCCAGAGAATTTCAATTTGGTTTTT"
        "GAGCAGTTTTTTTTGTCTAATATAAATTACACATATCAGATTTGGAAAAAAGGCTAA"
    ),

    "cmla1": (
        "GTGAGCTCAAAAAACTTTAGTTGGCGGTACTCCCTTGCCGCCACGGTGTTGTTGTTATCACCGTTCGATTTATTGGCATCACT"
        "CGGCATGGACATGTACTTGCCAGCAGTGCCGTTTATGCCAAACGCGCTTGGTACGACAGCGAGCACAATTCAGCTTACGCTGA"
        "CAACGTACTTGGTCATGATTGGTGCCGGTCAGCTCTTGTTTGGACCGCTATCGGACCGACTGGGGCGCCGCCCCGTTCTACTG"
        "GGAGGTGGCCTCGCCTACGTTGTGGCGTCAATGGGCCTCGCTCTTACGTCATCGGCTGAAGTCTTTCTGGGGCTTCGGATTCTT"
        "CAGGCTTGTGGTGCCTCGGCGTGCCTTGTTTCCACATTTGCAACAGTACGTGACATTTACGCAGGTCGCGAGGAAAGTAATGTC"
        "ATTTACGGCATACTCGGATCCATGCTGGCCATGGTCCCGGCGGTAGGCCCATTGCTCGGAGCGCTCGTCGACATGTGGCTTGGG"
        "TGGCGGGCTATCTTTGCGTTTCTAGGTTTGGGCATGATCGCTGCATCTGCAGCAGCGTGGCGATTCTGGCCTGAAACCCGGGTG"
        "CAACGAGTTGCGGGCTTGCAATGGTCGCAGCTGCTACTCCCCGTTAAGTGCCTGAACTTCTGGTTGTACACGTTGTGTTACGCC"
        "GCTGGAATGGGTAGCTTCTTCGTCTTTTTCTCCATTGCGCCCGGACTAATGATGGGCAGGCAAGGTGTGTCTCAGCTTGGCTTC"
        "AGCCTGCTGTTCGCCACAGTGGCAATTGCCATGGTGTTTACGGCTCGTTTTATGGGGCGTGTGATACCCAAGTGGGGCAGCCCA"
        "AGTGTCTTGCGAATGGGAATGGGATGCCTGATAGCTGGAGCAGTATTGCTTGCCATCACCGAAATATGGGCTTTGCAGTCCGTG"
        "TTAGGCTTTATTGCTCCAATGTGGCTAGTGGGTATTGGTGTCGCCACAGCGGTATCTGTGGCGCCCAATGGCGCTCTTCGAGGA"
        "TTCGACCATGTTGCTGGAACGGTCACGGCAGTCTACTTCTGCTTGGGCGGTGTACTGCTAGGAAGCATCGGAACGTTGATCATT"
        "TCGCTGTTGCCGCGCAACACGGCTTGGCCGGTTGTCGTGTACTGTTTGACCCTTGCAACAGTCGTGCTCGGTCTGTCTTGTGTT"
        "TCCCGAGTGAAGGGCTCTCGCGGCCAGGGGGAGCATGATGTGGTCGCGCTACAAAGTGCGGGAAGTACATCAAATCCCAATCGT"
        "TGA"
    ),

    # blaHER-3 — CARD HER-1 reference (closest available; HER family)
    "blaher-3": (
        "ATGAAGAAAATCGGCCTGGCCCTGGCGCTGACAGTGTCGGTGACGGCAGCCGCCCAGCACGATGATGTCCGGCAGAAACTCGC"
        "CGAGCTGGAGCGCAGGAGTGGCGGACGCCTGGGGGTGGCCCTGATCGACACCGCAGGCGGCGAGCAGGAACTGTACCGCGCCG"
        "ACGACCGCTTTGCGCTGTCCAGCACCAGCAAGGTGATGGCCGTGGCGGCGGTGCTGAAGAAGAGCGAGAGCGAGCCCAACCTG"
        "CTCGGCCAGCGCATCCAGATCAGCCGCTCGGACCTGGTCAACTACAACCCGATCGCCGAAAAGCACGTGGACGGCACCATGCCC"
        "CTGGCAGAGCTCAGCGCCGCCGCGCTGCAGTACAGCGACAACGTGGCGATGAACAAGCTCATCAGCCACGTGGGCGGCCCCGGC"
        "AGCGTGGCGGCCTTCGCCAGCCAGCTGGGCGACGAGACGTTCCGCCTGGACCGGACCGAGCCCACGCTGAACACCGCGATCCCG"
        "AGCGACCCGCGCGACACCACCAGCCCCAGGGCCATGGCGCAGACCCTGCGCAACCTGACGCTGGGCAAGGCGCTGGGCGACAGC"
        "CAGCGCGCGCAGCTGGTGACCTGGATGAAGGGCAACACCACGGGGGCGGCGAGCATCCAGGCCGGCCTGCCGCCGTACTGGGTT"
        "GTGGGCGACAAGACCGGCAGCGGCGACTACGGCACCACCAACGACATCGCGGTGATCTGGCCCAAGGACCGGGCCCCCCTGATC"
        "CTGGTGACCTACTTCACCCAGCCGCAGCCCAAGGCGGAGAGCCGCCGCGACGTGCTGGCAAGCGCGGCGAAAATCGTGACCAGC"
        "GGCTTC"
    ),

    "dfra51": (
        "TTGAAAAAATCATTGATTTCTGCAACATCAGAAAATGGTGTAATCGGCAATGGCCCTGATATTCCATGGTCAGCAAAAGGAGAG"
        "CAGTTACTCTTTAAAGCACTCACATATAATCAGTGGCTCCTGGTCGGAAGGAAAACATTTGACTCTATGGGTGTTCTTCCAAAT"
        "CGAAAATATGCAATAGTGTCGAGGAAAGGAATTTCGAGCTCAGATGAAAATGTGTTGGTCTTTCCTTCAATAGAAATCGCTTTG"
        "CAAGAACTGTCAAAAATTACAGATCATTTATATGTCTCTGGTGGCGGTCAAATATACAATAGTCTTATTGAAAAAGCAGATATA"
        "ATTCATTTGTCTACTGTTCACGTTGAAGTTGAAGGTGATATCAATTTTCCTAAAATTCCAGAGAATTTCAACTTGGTTTTTGAGC"
        "AGTTTTTTTTGTCTAATATAAATTACACTTATCAGATTTGGAAAAAAGGCTAA"
    ),
}

def clean_seq(s):
    """Remove whitespace, uppercase."""
    return "".join(s.split()).upper()

def validate(gene, seq):
    invalid = set(seq) - set("ATCGN")
    if invalid:
        print(f"  ⚠ {gene}: INVALID chars {invalid}")
        return False
    if len(seq) < 15:
        print(f"  ⚠ {gene}: Too short ({len(seq)} bp)")
        return False
    return True

# ================================================================
# PHASE 1: Fetch blaSHV-1 from NCBI (base conda has biopython)
# ================================================================
print("=" * 65)
print("PHASE 1: Fetching blaSHV-1 from NCBI (NG_048831.1 RefSeq)")
print("=" * 65)

blashv1_seq = None
try:
    handle = Entrez.efetch(db="nucleotide", id="NG_048831", rettype="gb", retmode="text")
    record = SeqIO.read(handle, "genbank")
    handle.close()
    cds_features = [f for f in record.features if f.type == "CDS"]
    if cds_features:
        cds = max(cds_features, key=lambda f: len(f.location))
        blashv1_seq = clean_seq(str(cds.extract(record.seq)))
        print(f"  ✅ blaSHV-1: {len(blashv1_seq)} bp from NG_048831.1")
    else:
        print("  ⚠ No CDS found in NG_048831.1 — trying J03265")
        handle2 = Entrez.efetch(db="nucleotide", id="J03265", rettype="gb", retmode="text")
        record2 = SeqIO.read(handle2, "genbank")
        handle2.close()
        cds2 = [f for f in record2.features if f.type == "CDS"]
        if cds2:
            blashv1_seq = clean_seq(str(max(cds2, key=lambda f: len(f.location)).extract(record2.seq)))
            print(f"  ✅ blaSHV-1: {len(blashv1_seq)} bp from J03265")
except Exception as e:
    print(f"  ❌ NCBI fetch failed: {e}")

# ================================================================
# PHASE 2: Update DB
# ================================================================
print(f"\n{'='*65}")
print("PHASE 2: Updating resistance_genes.db")
print("=" * 65)

conn = sqlite3.connect(r"db/resistance_genes.db")
cursor = conn.cursor()
cursor.execute("SELECT gene_name, dna_sequence FROM sequences")
all_genes = {row[0]: row[1] for row in cursor.fetchall()}

updated = 0
skipped = 0

for db_gene_name, db_seq in all_genes.items():
    key = db_gene_name.lower().strip()

    # ---- Fix blashv-1 ----
    if key == "blashv-1":
        if blashv1_seq and validate("blashv-1", blashv1_seq):
            cursor.execute("UPDATE sequences SET dna_sequence = ? WHERE gene_name = ?",
                           (blashv1_seq, db_gene_name))
            print(f"  ✅ {db_gene_name}: replaced with NCBI blaSHV-1 ({len(blashv1_seq)} bp)")
            updated += 1
        else:
            # Fallback: strip everything before the first ATG in the corrupted value
            raw = db_seq or ""
            match = re.search(r'ATG[ATCGN]+', raw.upper())
            if match:
                candidate = re.sub(r'[^ATCGN]', '', match.group())
                if validate("blashv-1 (recovered)", candidate):
                    cursor.execute("UPDATE sequences SET dna_sequence = ? WHERE gene_name = ?",
                                   (candidate, db_gene_name))
                    print(f"  ⚠ {db_gene_name}: used recovered ATG-stripped sequence ({len(candidate)} bp)")
                    updated += 1
                else:
                    print(f"  ❌ {db_gene_name}: Could not fix — leaving unchanged")
                    skipped += 1
            else:
                print(f"  ❌ {db_gene_name}: No valid ATG found — leaving unchanged")
                skipped += 1
        continue

    # ---- Fix blaTEM-1_variant ----
    if key == "blatem-1_variant":
        if db_seq:
            fixed = clean_seq(db_seq.replace(".", ""))
            if validate("blaTEM-1_variant", fixed):
                cursor.execute("UPDATE sequences SET dna_sequence = ? WHERE gene_name = ?",
                               (fixed, db_gene_name))
                print(f"  ✅ {db_gene_name}: removed '.' character ({len(fixed)} bp)")
                updated += 1
            else:
                print(f"  ❌ {db_gene_name}: still invalid after fix")
                skipped += 1
        continue

    # ---- Populate from browser-collected sequences ----
    if key in SEQUENCES:
        new_seq = clean_seq(SEQUENCES[key])
        if validate(key, new_seq):
            cursor.execute("UPDATE sequences SET dna_sequence = ? WHERE gene_name = ?",
                           (new_seq, db_gene_name))
            print(f"  ✅ {db_gene_name}: {len(new_seq)} bp")
            updated += 1
        else:
            skipped += 1
        continue

    # ---- SNP marker genes — flag only, do not touch ----
    if key in ("blatemp_c32t", "nfsa_q113ter", "uhpt_e350q"):
        print(f"  ℹ {db_gene_name}: SNP marker — requires literature sequence (skipped)")
        skipped += 1

conn.commit()
conn.close()

print(f"\n{'='*65}")
print(f"COMPLETE: {updated} genes updated, {skipped} skipped/flagged")
print("Genes still requiring manual sequences:")
print("  - blatemp_c32t  (TEM promoter C32T mutation region)")
print("  - nfsa_q113ter  (NfsA Q113stop codon region)")
print("  - uhpt_e350q    (UhpT E350Q mutation region)")
print("=" * 65)
